<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Carbon\Carbon;
use Illuminate\Support\Facades\File;

class ReportExportNotification extends Notification
{
    use Queueable;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        $misReportPath = storage_path('app/home/forge/mis.shiprider.in/storage/app/public/mis');
        $files = File::files($misReportPath);
    
        date_default_timezone_set('Asia/Kolkata');
    
        $today = now();
        $todaydDate = $today->format('d-M-Y');
    
        $mailMessage = (new MailMessage)
            ->subject('Daily MIS2 Report  ' . $todaydDate)
            ->line('Please find the attached daily MIS2 Reports. This report has been generated by our system and includes data of last 3 months.');
    
        foreach ($files as $file) {
            $mailMessage->attach($file);
        }
    
        return $mailMessage;
    }
    

    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            //
        ];
    }
}
