<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Carbon\Carbon;

class ReportExportNotification extends Notification
{
    use Queueable;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        $path = storage_path('app/public/mis/mis2.xlsx');
        date_default_timezone_set('Asia/Kolkata');
        $current_time = date("h:i A");
        $currentDate = Carbon::now();
        // Format the date as "12-Oct-2023"
        $formattedDate = $currentDate->format('d-M-Y');
        return (new MailMessage)
                    ->line('Please find the attached Daily MIS2 Report. This report has been generated by our system and includes data from the last 45 days up to '.$formattedDate. ' at ' . $current_time)
                    ->attach($path, [
                        'as' => 'mis2.xlsx'
                    ]);
    }
    

    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            //
        ];
    }
}
